name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service health endpoint
        env:
          KEEPALIVE_URL: ${{ secrets.KEEPALIVE_URL }}
        run: |
          if [ -z "$KEEPALIVE_URL" ]; then
            echo "KEEPALIVE_URL secret is not set. Set it in repository settings."
            exit 1
          fi
          echo "Pinging $KEEPALIVE_URL ..."
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$KEEPALIVE_URL")
          echo "HTTP $HTTP_CODE"
          if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 400 ]; then
            echo "Ping failed with HTTP code $HTTP_CODE"
            exit 1
          fi
          echo "Ping OK"
