name: Health Pinger

on:
  schedule:
    - cron: "*/5 * * * *"   # Otomatik (UTC)
  workflow_dispatch: {}      # Manuel tetikleme butonu için şart

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit health endpoint
        run: |
          curl -sS -m 20 --retry 2 --retry-delay 5 \
            -H "User-Agent: gh-actions-pinger" \
            "https://x-to-reddit-bot.onrender.com/healthz"
