      - name: Ping health endpoint (secret)
        run: |
          curl -sS -m 20 --retry 2 --retry-delay 5 \
            -H "User-Agent: gh-actions-pinger" \
            "${{ secrets.KEEPALIVE_URL }}"
