name: Health Pinger

on:
  schedule:
    - cron: "* * * * *"  # Her dakika (UTC)

concurrency:
  group: health-pinger
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit health endpoint
        run: |
          curl -sS -m 20 --retry 2 --retry-delay 5 \
            -H "User-Agent: gh-actions-pinger" \
            "https://x-to-reddit-bot.onrender.com/healthz"
